"""tranche table

Revision ID: 634b379a9939
Revises: 0a83904485f5
Create Date: 2022-01-03 16:08:06.082795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634b379a9939'
down_revision = '0a83904485f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tranche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tranche_symbol'), 'tranche', ['symbol'], unique=False)
    op.create_index(op.f('ix_tranche_timestamp'), 'tranche', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tranche_timestamp'), table_name='tranche')
    op.drop_index(op.f('ix_tranche_symbol'), table_name='tranche')
    op.drop_table('tranche')
    # ### end Alembic commands ###
